# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

stages:
  - build


compile:
  stage: build
  tags:
    - gl_router_runner
  only:
    refs:
      - master
  script:
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_DIR
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_COMMIT_MESSAGE
    - cd /home/luo/runner-script/sdk4_script;./sdk4_compile_ci "$CI_PROJECT_NAME" "$CI_PROJECT_DIR" "$CI_COMMIT_SHORT_SHA" "$CI_COMMIT_MESSAGE"

